name = "PersistentArrays"
uuid = "0bd6e0f1-f413-4adc-84f9-e31ccad13b82"
authors = ["Mark Hildebrand <mhildebrand@ucdavis.edu>"]
version = "0.1.0"

[deps]
LibGit2 = "76f85450-5226-5b5a-8eaa-529ad045b433"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
